/**
 * Country name → ISO 3166-1 alpha-2 code.
 *
 * Fallback for ship-to locations that have a country *name* but no country
 * *code* — e.g. workbooks with a "Country" column but no "Country Code"
 * column. Carrier rate APIs require the code, so the import and the quote
 * flow derive it from the name when the code is blank.
 *
 * Keep keys lowercase, no periods, single spaces. Matching is
 * case-insensitive and ignores surrounding whitespace and periods.
 */
const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  canada: 'CA',
  'united states': 'US',
  'united states of america': 'US',
  usa: 'US',
  us: 'US',
  'u s a': 'US',
  mexico: 'MX',
  greenland: 'GL',
  'saint pierre and miquelon': 'PM',
  guatemala: 'GT',
  belize: 'BZ',
  honduras: 'HN',
  'el salvador': 'SV',
  nicaragua: 'NI',
  'costa rica': 'CR',
  panama: 'PA',
  bahamas: 'BS',
  cuba: 'CU',
  jamaica: 'JM',
  haiti: 'HT',
  'dominican republic': 'DO',
  'puerto rico': 'PR',
  'trinidad and tobago': 'TT',
  barbados: 'BB',
  bermuda: 'BM',
  'cayman islands': 'KY',
  'virgin islands': 'VI',
  'us virgin islands': 'VI',
  aruba: 'AW',
  curacao: 'CW',
  brazil: 'BR',
  argentina: 'AR',
  chile: 'CL',
  colombia: 'CO',
  peru: 'PE',
  venezuela: 'VE',
  ecuador: 'EC',
  bolivia: 'BO',
  paraguay: 'PY',
  uruguay: 'UY',
  guyana: 'GY',
  suriname: 'SR',
  'united kingdom': 'GB',
  uk: 'GB',
  'u k': 'GB',
  'great britain': 'GB',
  britain: 'GB',
  england: 'GB',
  ireland: 'IE',
  france: 'FR',
  germany: 'DE',
  italy: 'IT',
  spain: 'ES',
  portugal: 'PT',
  netherlands: 'NL',
  holland: 'NL',
  belgium: 'BE',
  luxembourg: 'LU',
  switzerland: 'CH',
  austria: 'AT',
  sweden: 'SE',
  norway: 'NO',
  denmark: 'DK',
  finland: 'FI',
  iceland: 'IS',
  poland: 'PL',
  'czech republic': 'CZ',
  czechia: 'CZ',
  slovakia: 'SK',
  hungary: 'HU',
  romania: 'RO',
  bulgaria: 'BG',
  greece: 'GR',
  croatia: 'HR',
  slovenia: 'SI',
  serbia: 'RS',
  bosnia: 'BA',
  'bosnia and herzegovina': 'BA',
  albania: 'AL',
  macedonia: 'MK',
  'north macedonia': 'MK',
  estonia: 'EE',
  latvia: 'LV',
  lithuania: 'LT',
  ukraine: 'UA',
  moldova: 'MD',
  belarus: 'BY',
  russia: 'RU',
  'russian federation': 'RU',
  turkey: 'TR',
  turkiye: 'TR',
  cyprus: 'CY',
  malta: 'MT',
  israel: 'IL',
  'united arab emirates': 'AE',
  uae: 'AE',
  'saudi arabia': 'SA',
  qatar: 'QA',
  kuwait: 'KW',
  oman: 'OM',
  bahrain: 'BH',
  jordan: 'JO',
  lebanon: 'LB',
  egypt: 'EG',
  morocco: 'MA',
  algeria: 'DZ',
  tunisia: 'TN',
  libya: 'LY',
  nigeria: 'NG',
  ghana: 'GH',
  kenya: 'KE',
  ethiopia: 'ET',
  tanzania: 'TZ',
  uganda: 'UG',
  'south africa': 'ZA',
  china: 'CN',
  'hong kong': 'HK',
  macau: 'MO',
  taiwan: 'TW',
  japan: 'JP',
  'south korea': 'KR',
  korea: 'KR',
  'korea south': 'KR',
  mongolia: 'MN',
  singapore: 'SG',
  malaysia: 'MY',
  thailand: 'TH',
  vietnam: 'VN',
  philippines: 'PH',
  indonesia: 'ID',
  cambodia: 'KH',
  laos: 'LA',
  myanmar: 'MM',
  burma: 'MM',
  india: 'IN',
  pakistan: 'PK',
  bangladesh: 'BD',
  'sri lanka': 'LK',
  nepal: 'NP',
  bhutan: 'BT',
  australia: 'AU',
  'new zealand': 'NZ',
  fiji: 'FJ',
  'papua new guinea': 'PG',
  guam: 'GU',
};

/**
 * Derive an ISO alpha-2 country code from a country name. Returns null when
 * the name is blank or not recognized.
 */
export function countryCodeFromName(
  raw: string | null | undefined,
): string | null {
  if (!raw) return null;
  const key = raw
    .trim()
    .toLowerCase()
    .replace(/\./g, '')
    .replace(/\s+/g, ' ');
  if (!key) return null;
  return COUNTRY_NAME_TO_CODE[key] ?? null;
}
